apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: ricardonok
spec:
  controllerName: demo.rkatz.xyz/controller
  parametersRef:
    group: v1
    kind: Secret
    name: class-config
    namespace: default
