apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: ricardowithref
spec:
  controllerName: demo.rkatz.xyz/controller
  parametersRef:
    group: v1
    kind: ConfigMap
    name: class-config
    namespace: default
